/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BitesGeoListFormatParameter } from '../models';
// @ts-ignore
import type { BitesListFormatParameter } from '../models';
// @ts-ignore
import type { BitesListOrderByParameter } from '../models';
// @ts-ignore
import type { BreedingSite } from '../models';
// @ts-ignore
import type { BreedingSiteGeoJsonModelList } from '../models';
// @ts-ignore
import type { BreedingSiteGeoModel } from '../models';
// @ts-ignore
import type { BreedingSiteRequestSiteType } from '../models';
// @ts-ignore
import type { BreedingsitesCreateValidationError } from '../models';
// @ts-ignore
import type { BreedingsitesGeoListValidationError } from '../models';
// @ts-ignore
import type { BreedingsitesListMineValidationError } from '../models';
// @ts-ignore
import type { BreedingsitesListSiteTypeParameter } from '../models';
// @ts-ignore
import type { BreedingsitesListValidationError } from '../models';
// @ts-ignore
import type { ErrorResponse401 } from '../models';
// @ts-ignore
import type { ErrorResponse403 } from '../models';
// @ts-ignore
import type { ErrorResponse404 } from '../models';
// @ts-ignore
import type { LocationRequest } from '../models';
// @ts-ignore
import type { PaginatedBreedingSiteList } from '../models';
/**
 * BreedingSitesApi - axios parameter creator
 */
export const BreedingSitesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} createdAt 
         * @param {string} sentAt 
         * @param {LocationRequest} location 
         * @param {Array<File>} photos 
         * @param {BreedingSiteRequestSiteType} siteType 
         * @param {string | null} [note] 
         * @param {Array<string>} [tags] 
         * @param {boolean | null} [hasWater] Either if the user perceived water in the breeding site.
         * @param {boolean | null} [inPublicArea] Either if the breeding site is found in a public area.
         * @param {boolean | null} [hasNearMosquitoes] Either if the user perceived mosquitoes near the breeding site (less than 10 meters).
         * @param {boolean | null} [hasLarvae] Either if the user perceived larvaes the breeding site.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createdAt: string, sentAt: string, location: LocationRequest, photos: Array<File>, siteType: BreedingSiteRequestSiteType, note?: string | null, tags?: Array<string>, hasWater?: boolean | null, inPublicArea?: boolean | null, hasNearMosquitoes?: boolean | null, hasLarvae?: boolean | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createdAt' is not null or undefined
            assertParamExists('create', 'createdAt', createdAt)
            // verify required parameter 'sentAt' is not null or undefined
            assertParamExists('create', 'sentAt', sentAt)
            // verify required parameter 'location' is not null or undefined
            assertParamExists('create', 'location', location)
            // verify required parameter 'photos' is not null or undefined
            assertParamExists('create', 'photos', photos)
            // verify required parameter 'siteType' is not null or undefined
            assertParamExists('create', 'siteType', siteType)
            const localVarPath = `/breeding-sites/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (createdAt !== undefined) { 
                localVarFormParams.append('created_at', createdAt as any);
            }

            if (sentAt !== undefined) { 
                localVarFormParams.append('sent_at', sentAt as any);
            }

            if (location !== undefined) { 
                localVarFormParams.append('location', new Blob([JSON.stringify(location, replaceWithSerializableTypeIfNeeded)], { type: "application/json", }));
            }

            if (note !== undefined) { 
                localVarFormParams.append('note', note as any);
            }
            if (tags) {
                localVarFormParams.append('tags', tags.join(COLLECTION_FORMATS.csv));
            }

            if (photos) {
                photos.forEach((element) => {
                    localVarFormParams.append('photos', element as any);
                })
            }


            if (siteType !== undefined) { 
                localVarFormParams.append('site_type', siteType as any);
            }

            if (hasWater !== undefined) { 
                localVarFormParams.append('has_water', String(hasWater) as any);
            }

            if (inPublicArea !== undefined) { 
                localVarFormParams.append('in_public_area', String(inPublicArea) as any);
            }

            if (hasNearMosquitoes !== undefined) { 
                localVarFormParams.append('has_near_mosquitoes', String(hasNearMosquitoes) as any);
            }

            if (hasLarvae !== undefined) { 
                localVarFormParams.append('has_larvae', String(hasLarvae) as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        destroy: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('destroy', 'uuid', uuid)
            const localVarPath = `/breeding-sites/{uuid}/`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesGeoListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasLarvae] 
         * @param {boolean} [hasNearMosquitoes] 
         * @param {boolean} [hasPhotos] Has any photo
         * @param {boolean} [hasWater] 
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<BreedingsitesListSiteTypeParameter>} [siteType] Breeding site type.  
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geoList: async (boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesGeoListFormatParameter, geoPrecision?: number, hasLarvae?: boolean, hasNearMosquitoes?: boolean, hasPhotos?: boolean, hasWater?: boolean, orderBy?: Array<BitesListOrderByParameter>, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, siteType?: Array<BreedingsitesListSiteTypeParameter>, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/breeding-sites/geo/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (boundaryUuid !== undefined) {
                localVarQueryParameter['boundary_uuid'] = boundaryUuid;
            }

            if (countryId !== undefined) {
                localVarQueryParameter['country_id'] = countryId;
            }

            if (createdAtAfter !== undefined) {
                localVarQueryParameter['created_at_after'] = (createdAtAfter as any instanceof Date) ?
                    (createdAtAfter as any).toISOString() :
                    createdAtAfter;
            }

            if (createdAtBefore !== undefined) {
                localVarQueryParameter['created_at_before'] = (createdAtBefore as any instanceof Date) ?
                    (createdAtBefore as any).toISOString() :
                    createdAtBefore;
            }

            if (dist !== undefined) {
                localVarQueryParameter['dist'] = dist;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (geoPrecision !== undefined) {
                localVarQueryParameter['geo_precision'] = geoPrecision;
            }

            if (hasLarvae !== undefined) {
                localVarQueryParameter['has_larvae'] = hasLarvae;
            }

            if (hasNearMosquitoes !== undefined) {
                localVarQueryParameter['has_near_mosquitoes'] = hasNearMosquitoes;
            }

            if (hasPhotos !== undefined) {
                localVarQueryParameter['has_photos'] = hasPhotos;
            }

            if (hasWater !== undefined) {
                localVarQueryParameter['has_water'] = hasWater;
            }

            if (orderBy) {
                localVarQueryParameter['order_by'] = orderBy.join(COLLECTION_FORMATS.csv);
            }

            if (point) {
                localVarQueryParameter['point'] = point.join(COLLECTION_FORMATS.csv);
            }

            if (receivedAtAfter !== undefined) {
                localVarQueryParameter['received_at_after'] = (receivedAtAfter as any instanceof Date) ?
                    (receivedAtAfter as any).toISOString() :
                    receivedAtAfter;
            }

            if (receivedAtBefore !== undefined) {
                localVarQueryParameter['received_at_before'] = (receivedAtBefore as any instanceof Date) ?
                    (receivedAtBefore as any).toISOString() :
                    receivedAtBefore;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (shortId !== undefined) {
                localVarQueryParameter['short_id'] = shortId;
            }

            if (siteType) {
                localVarQueryParameter['site_type'] = siteType;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (updatedAtAfter !== undefined) {
                localVarQueryParameter['updated_at_after'] = (updatedAtAfter as any instanceof Date) ?
                    (updatedAtAfter as any).toISOString() :
                    updatedAtAfter;
            }

            if (updatedAtBefore !== undefined) {
                localVarQueryParameter['updated_at_before'] = (updatedAtBefore as any instanceof Date) ?
                    (updatedAtBefore as any).toISOString() :
                    updatedAtBefore;
            }

            if (userUuid !== undefined) {
                localVarQueryParameter['user_uuid'] = userUuid;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/geo+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasLarvae] 
         * @param {boolean} [hasNearMosquitoes] 
         * @param {boolean} [hasPhotos] Has any photo
         * @param {boolean} [hasWater] 
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<BreedingsitesListSiteTypeParameter>} [siteType] Breeding site type.  
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasLarvae?: boolean, hasNearMosquitoes?: boolean, hasPhotos?: boolean, hasWater?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, siteType?: Array<BreedingsitesListSiteTypeParameter>, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/breeding-sites/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (boundaryUuid !== undefined) {
                localVarQueryParameter['boundary_uuid'] = boundaryUuid;
            }

            if (countryId !== undefined) {
                localVarQueryParameter['country_id'] = countryId;
            }

            if (createdAtAfter !== undefined) {
                localVarQueryParameter['created_at_after'] = (createdAtAfter as any instanceof Date) ?
                    (createdAtAfter as any).toISOString() :
                    createdAtAfter;
            }

            if (createdAtBefore !== undefined) {
                localVarQueryParameter['created_at_before'] = (createdAtBefore as any instanceof Date) ?
                    (createdAtBefore as any).toISOString() :
                    createdAtBefore;
            }

            if (dist !== undefined) {
                localVarQueryParameter['dist'] = dist;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (geoPrecision !== undefined) {
                localVarQueryParameter['geo_precision'] = geoPrecision;
            }

            if (hasLarvae !== undefined) {
                localVarQueryParameter['has_larvae'] = hasLarvae;
            }

            if (hasNearMosquitoes !== undefined) {
                localVarQueryParameter['has_near_mosquitoes'] = hasNearMosquitoes;
            }

            if (hasPhotos !== undefined) {
                localVarQueryParameter['has_photos'] = hasPhotos;
            }

            if (hasWater !== undefined) {
                localVarQueryParameter['has_water'] = hasWater;
            }

            if (orderBy) {
                localVarQueryParameter['order_by'] = orderBy.join(COLLECTION_FORMATS.csv);
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (point) {
                localVarQueryParameter['point'] = point.join(COLLECTION_FORMATS.csv);
            }

            if (receivedAtAfter !== undefined) {
                localVarQueryParameter['received_at_after'] = (receivedAtAfter as any instanceof Date) ?
                    (receivedAtAfter as any).toISOString() :
                    receivedAtAfter;
            }

            if (receivedAtBefore !== undefined) {
                localVarQueryParameter['received_at_before'] = (receivedAtBefore as any instanceof Date) ?
                    (receivedAtBefore as any).toISOString() :
                    receivedAtBefore;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (shortId !== undefined) {
                localVarQueryParameter['short_id'] = shortId;
            }

            if (siteType) {
                localVarQueryParameter['site_type'] = siteType;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (updatedAtAfter !== undefined) {
                localVarQueryParameter['updated_at_after'] = (updatedAtAfter as any instanceof Date) ?
                    (updatedAtAfter as any).toISOString() :
                    updatedAtAfter;
            }

            if (updatedAtBefore !== undefined) {
                localVarQueryParameter['updated_at_before'] = (updatedAtBefore as any instanceof Date) ?
                    (updatedAtBefore as any).toISOString() :
                    updatedAtBefore;
            }

            if (userUuid !== undefined) {
                localVarQueryParameter['user_uuid'] = userUuid;
            }

            localVarHeaderParameter['Accept'] = 'application/json,text/csv';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Current User\'s Breeding Sites
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasLarvae] 
         * @param {boolean} [hasNearMosquitoes] 
         * @param {boolean} [hasPhotos] Has any photo
         * @param {boolean} [hasWater] 
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<BreedingsitesListSiteTypeParameter>} [siteType] Breeding site type.  
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMine: async (boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasLarvae?: boolean, hasNearMosquitoes?: boolean, hasPhotos?: boolean, hasWater?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, siteType?: Array<BreedingsitesListSiteTypeParameter>, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/me/breeding-sites/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (boundaryUuid !== undefined) {
                localVarQueryParameter['boundary_uuid'] = boundaryUuid;
            }

            if (countryId !== undefined) {
                localVarQueryParameter['country_id'] = countryId;
            }

            if (createdAtAfter !== undefined) {
                localVarQueryParameter['created_at_after'] = (createdAtAfter as any instanceof Date) ?
                    (createdAtAfter as any).toISOString() :
                    createdAtAfter;
            }

            if (createdAtBefore !== undefined) {
                localVarQueryParameter['created_at_before'] = (createdAtBefore as any instanceof Date) ?
                    (createdAtBefore as any).toISOString() :
                    createdAtBefore;
            }

            if (dist !== undefined) {
                localVarQueryParameter['dist'] = dist;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (geoPrecision !== undefined) {
                localVarQueryParameter['geo_precision'] = geoPrecision;
            }

            if (hasLarvae !== undefined) {
                localVarQueryParameter['has_larvae'] = hasLarvae;
            }

            if (hasNearMosquitoes !== undefined) {
                localVarQueryParameter['has_near_mosquitoes'] = hasNearMosquitoes;
            }

            if (hasPhotos !== undefined) {
                localVarQueryParameter['has_photos'] = hasPhotos;
            }

            if (hasWater !== undefined) {
                localVarQueryParameter['has_water'] = hasWater;
            }

            if (orderBy) {
                localVarQueryParameter['order_by'] = orderBy.join(COLLECTION_FORMATS.csv);
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (point) {
                localVarQueryParameter['point'] = point.join(COLLECTION_FORMATS.csv);
            }

            if (receivedAtAfter !== undefined) {
                localVarQueryParameter['received_at_after'] = (receivedAtAfter as any instanceof Date) ?
                    (receivedAtAfter as any).toISOString() :
                    receivedAtAfter;
            }

            if (receivedAtBefore !== undefined) {
                localVarQueryParameter['received_at_before'] = (receivedAtBefore as any instanceof Date) ?
                    (receivedAtBefore as any).toISOString() :
                    receivedAtBefore;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (shortId !== undefined) {
                localVarQueryParameter['short_id'] = shortId;
            }

            if (siteType) {
                localVarQueryParameter['site_type'] = siteType;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (updatedAtAfter !== undefined) {
                localVarQueryParameter['updated_at_after'] = (updatedAtAfter as any instanceof Date) ?
                    (updatedAtAfter as any).toISOString() :
                    updatedAtAfter;
            }

            if (updatedAtBefore !== undefined) {
                localVarQueryParameter['updated_at_before'] = (updatedAtBefore as any instanceof Date) ?
                    (updatedAtBefore as any).toISOString() :
                    updatedAtBefore;
            }

            if (userUuid !== undefined) {
                localVarQueryParameter['user_uuid'] = userUuid;
            }

            localVarHeaderParameter['Accept'] = 'application/json,text/csv';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieve: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('retrieve', 'uuid', uuid)
            const localVarPath = `/breeding-sites/{uuid}/`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BreedingSitesApi - functional programming interface
 */
export const BreedingSitesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BreedingSitesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} createdAt 
         * @param {string} sentAt 
         * @param {LocationRequest} location 
         * @param {Array<File>} photos 
         * @param {BreedingSiteRequestSiteType} siteType 
         * @param {string | null} [note] 
         * @param {Array<string>} [tags] 
         * @param {boolean | null} [hasWater] Either if the user perceived water in the breeding site.
         * @param {boolean | null} [inPublicArea] Either if the breeding site is found in a public area.
         * @param {boolean | null} [hasNearMosquitoes] Either if the user perceived mosquitoes near the breeding site (less than 10 meters).
         * @param {boolean | null} [hasLarvae] Either if the user perceived larvaes the breeding site.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createdAt: string, sentAt: string, location: LocationRequest, photos: Array<File>, siteType: BreedingSiteRequestSiteType, note?: string | null, tags?: Array<string>, hasWater?: boolean | null, inPublicArea?: boolean | null, hasNearMosquitoes?: boolean | null, hasLarvae?: boolean | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BreedingSite>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createdAt, sentAt, location, photos, siteType, note, tags, hasWater, inPublicArea, hasNearMosquitoes, hasLarvae, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BreedingSitesApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async destroy(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.destroy(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BreedingSitesApi.destroy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesGeoListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasLarvae] 
         * @param {boolean} [hasNearMosquitoes] 
         * @param {boolean} [hasPhotos] Has any photo
         * @param {boolean} [hasWater] 
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<BreedingsitesListSiteTypeParameter>} [siteType] Breeding site type.  
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geoList(boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesGeoListFormatParameter, geoPrecision?: number, hasLarvae?: boolean, hasNearMosquitoes?: boolean, hasPhotos?: boolean, hasWater?: boolean, orderBy?: Array<BitesListOrderByParameter>, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, siteType?: Array<BreedingsitesListSiteTypeParameter>, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BreedingSiteGeoModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geoList(boundaryUuid, countryId, createdAtAfter, createdAtBefore, dist, format, geoPrecision, hasLarvae, hasNearMosquitoes, hasPhotos, hasWater, orderBy, point, receivedAtAfter, receivedAtBefore, search, shortId, siteType, tags, updatedAtAfter, updatedAtBefore, userUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BreedingSitesApi.geoList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasLarvae] 
         * @param {boolean} [hasNearMosquitoes] 
         * @param {boolean} [hasPhotos] Has any photo
         * @param {boolean} [hasWater] 
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<BreedingsitesListSiteTypeParameter>} [siteType] Breeding site type.  
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasLarvae?: boolean, hasNearMosquitoes?: boolean, hasPhotos?: boolean, hasWater?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, siteType?: Array<BreedingsitesListSiteTypeParameter>, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedBreedingSiteList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(boundaryUuid, countryId, createdAtAfter, createdAtBefore, dist, format, geoPrecision, hasLarvae, hasNearMosquitoes, hasPhotos, hasWater, orderBy, page, pageSize, point, receivedAtAfter, receivedAtBefore, search, shortId, siteType, tags, updatedAtAfter, updatedAtBefore, userUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BreedingSitesApi.list']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Current User\'s Breeding Sites
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasLarvae] 
         * @param {boolean} [hasNearMosquitoes] 
         * @param {boolean} [hasPhotos] Has any photo
         * @param {boolean} [hasWater] 
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<BreedingsitesListSiteTypeParameter>} [siteType] Breeding site type.  
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMine(boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasLarvae?: boolean, hasNearMosquitoes?: boolean, hasPhotos?: boolean, hasWater?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, siteType?: Array<BreedingsitesListSiteTypeParameter>, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedBreedingSiteList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMine(boundaryUuid, countryId, createdAtAfter, createdAtBefore, dist, format, geoPrecision, hasLarvae, hasNearMosquitoes, hasPhotos, hasWater, orderBy, page, pageSize, point, receivedAtAfter, receivedAtBefore, search, shortId, siteType, tags, updatedAtAfter, updatedAtBefore, userUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BreedingSitesApi.listMine']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieve(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BreedingSite>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieve(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BreedingSitesApi.retrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BreedingSitesApi - factory interface
 */
export const BreedingSitesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BreedingSitesApiFp(configuration)
    return {
        /**
         * 
         * @param {BreedingSitesApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(requestParameters: BreedingSitesApiCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BreedingSite> {
            return localVarFp.create(requestParameters.createdAt, requestParameters.sentAt, requestParameters.location, requestParameters.photos, requestParameters.siteType, requestParameters.note, requestParameters.tags, requestParameters.hasWater, requestParameters.inPublicArea, requestParameters.hasNearMosquitoes, requestParameters.hasLarvae, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BreedingSitesApiDestroyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        destroy(requestParameters: BreedingSitesApiDestroyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.destroy(requestParameters.uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BreedingSitesApiGeoListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geoList(requestParameters: BreedingSitesApiGeoListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<BreedingSiteGeoModel>> {
            return localVarFp.geoList(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasLarvae, requestParameters.hasNearMosquitoes, requestParameters.hasPhotos, requestParameters.hasWater, requestParameters.orderBy, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.siteType, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BreedingSitesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: BreedingSitesApiListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedBreedingSiteList> {
            return localVarFp.list(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasLarvae, requestParameters.hasNearMosquitoes, requestParameters.hasPhotos, requestParameters.hasWater, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.siteType, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Current User\'s Breeding Sites
         * @param {BreedingSitesApiListMineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMine(requestParameters: BreedingSitesApiListMineRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedBreedingSiteList> {
            return localVarFp.listMine(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasLarvae, requestParameters.hasNearMosquitoes, requestParameters.hasPhotos, requestParameters.hasWater, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.siteType, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BreedingSitesApiRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieve(requestParameters: BreedingSitesApiRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<BreedingSite> {
            return localVarFp.retrieve(requestParameters.uuid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for create operation in BreedingSitesApi.
 */
export interface BreedingSitesApiCreateRequest {
    readonly createdAt: string

    readonly sentAt: string

    readonly location: LocationRequest

    readonly photos: Array<File>

    readonly siteType: BreedingSiteRequestSiteType

    readonly note?: string | null

    readonly tags?: Array<string>

    /**
     * Either if the user perceived water in the breeding site.
     */
    readonly hasWater?: boolean | null

    /**
     * Either if the breeding site is found in a public area.
     */
    readonly inPublicArea?: boolean | null

    /**
     * Either if the user perceived mosquitoes near the breeding site (less than 10 meters).
     */
    readonly hasNearMosquitoes?: boolean | null

    /**
     * Either if the user perceived larvaes the breeding site.
     */
    readonly hasLarvae?: boolean | null
}

/**
 * Request parameters for destroy operation in BreedingSitesApi.
 */
export interface BreedingSitesApiDestroyRequest {
    readonly uuid: string
}

/**
 * Request parameters for geoList operation in BreedingSitesApi.
 */
export interface BreedingSitesApiGeoListRequest {
    readonly boundaryUuid?: string

    readonly countryId?: number

    /**
     * Created at
     */
    readonly createdAtAfter?: string

    /**
     * Created at
     */
    readonly createdAtBefore?: string

    /**
     * Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
     */
    readonly dist?: number

    readonly format?: BitesGeoListFormatParameter

    /**
     * Latitude/Longitude precision
     */
    readonly geoPrecision?: number

    readonly hasLarvae?: boolean

    readonly hasNearMosquitoes?: boolean

    /**
     * Has any photo
     */
    readonly hasPhotos?: boolean

    readonly hasWater?: boolean

    /**
     * Ordenamiento  
     */
    readonly orderBy?: Array<BitesListOrderByParameter>

    /**
     * Point represented in **x,y** format. Represents **point** in **Distance to point filter**
     */
    readonly point?: Array<number>

    /**
     * Received at
     */
    readonly receivedAtAfter?: string

    /**
     * Received at
     */
    readonly receivedAtBefore?: string

    /**
     * Un término de búsqueda.
     */
    readonly search?: string

    /**
     * Short ID
     */
    readonly shortId?: string

    /**
     * Breeding site type.  
     */
    readonly siteType?: Array<BreedingsitesListSiteTypeParameter>

    /**
     * Múltiples valores separados por comas.
     */
    readonly tags?: Array<string>

    /**
     * Update at
     */
    readonly updatedAtAfter?: string

    /**
     * Update at
     */
    readonly updatedAtBefore?: string

    readonly userUuid?: string
}

/**
 * Request parameters for list operation in BreedingSitesApi.
 */
export interface BreedingSitesApiListRequest {
    readonly boundaryUuid?: string

    readonly countryId?: number

    /**
     * Created at
     */
    readonly createdAtAfter?: string

    /**
     * Created at
     */
    readonly createdAtBefore?: string

    /**
     * Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
     */
    readonly dist?: number

    readonly format?: BitesListFormatParameter

    /**
     * Latitude/Longitude precision
     */
    readonly geoPrecision?: number

    readonly hasLarvae?: boolean

    readonly hasNearMosquitoes?: boolean

    /**
     * Has any photo
     */
    readonly hasPhotos?: boolean

    readonly hasWater?: boolean

    /**
     * Ordenamiento  
     */
    readonly orderBy?: Array<BitesListOrderByParameter>

    /**
     * Un número de página dentro del conjunto de resultados paginado.
     */
    readonly page?: number

    /**
     * Número de resultados a devolver por página.
     */
    readonly pageSize?: number

    /**
     * Point represented in **x,y** format. Represents **point** in **Distance to point filter**
     */
    readonly point?: Array<number>

    /**
     * Received at
     */
    readonly receivedAtAfter?: string

    /**
     * Received at
     */
    readonly receivedAtBefore?: string

    /**
     * Un término de búsqueda.
     */
    readonly search?: string

    /**
     * Short ID
     */
    readonly shortId?: string

    /**
     * Breeding site type.  
     */
    readonly siteType?: Array<BreedingsitesListSiteTypeParameter>

    /**
     * Múltiples valores separados por comas.
     */
    readonly tags?: Array<string>

    /**
     * Update at
     */
    readonly updatedAtAfter?: string

    /**
     * Update at
     */
    readonly updatedAtBefore?: string

    readonly userUuid?: string
}

/**
 * Request parameters for listMine operation in BreedingSitesApi.
 */
export interface BreedingSitesApiListMineRequest {
    readonly boundaryUuid?: string

    readonly countryId?: number

    /**
     * Created at
     */
    readonly createdAtAfter?: string

    /**
     * Created at
     */
    readonly createdAtBefore?: string

    /**
     * Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
     */
    readonly dist?: number

    readonly format?: BitesListFormatParameter

    /**
     * Latitude/Longitude precision
     */
    readonly geoPrecision?: number

    readonly hasLarvae?: boolean

    readonly hasNearMosquitoes?: boolean

    /**
     * Has any photo
     */
    readonly hasPhotos?: boolean

    readonly hasWater?: boolean

    /**
     * Ordenamiento  
     */
    readonly orderBy?: Array<BitesListOrderByParameter>

    /**
     * Un número de página dentro del conjunto de resultados paginado.
     */
    readonly page?: number

    /**
     * Número de resultados a devolver por página.
     */
    readonly pageSize?: number

    /**
     * Point represented in **x,y** format. Represents **point** in **Distance to point filter**
     */
    readonly point?: Array<number>

    /**
     * Received at
     */
    readonly receivedAtAfter?: string

    /**
     * Received at
     */
    readonly receivedAtBefore?: string

    /**
     * Un término de búsqueda.
     */
    readonly search?: string

    /**
     * Short ID
     */
    readonly shortId?: string

    /**
     * Breeding site type.  
     */
    readonly siteType?: Array<BreedingsitesListSiteTypeParameter>

    /**
     * Múltiples valores separados por comas.
     */
    readonly tags?: Array<string>

    /**
     * Update at
     */
    readonly updatedAtAfter?: string

    /**
     * Update at
     */
    readonly updatedAtBefore?: string

    readonly userUuid?: string
}

/**
 * Request parameters for retrieve operation in BreedingSitesApi.
 */
export interface BreedingSitesApiRetrieveRequest {
    readonly uuid: string
}

/**
 * BreedingSitesApi - object-oriented interface
 */
export class BreedingSitesApi extends BaseAPI {
    /**
     * 
     * @param {BreedingSitesApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(requestParameters: BreedingSitesApiCreateRequest, options?: RawAxiosRequestConfig) {
        return BreedingSitesApiFp(this.configuration).create(requestParameters.createdAt, requestParameters.sentAt, requestParameters.location, requestParameters.photos, requestParameters.siteType, requestParameters.note, requestParameters.tags, requestParameters.hasWater, requestParameters.inPublicArea, requestParameters.hasNearMosquitoes, requestParameters.hasLarvae, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BreedingSitesApiDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public destroy(requestParameters: BreedingSitesApiDestroyRequest, options?: RawAxiosRequestConfig) {
        return BreedingSitesApiFp(this.configuration).destroy(requestParameters.uuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BreedingSitesApiGeoListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public geoList(requestParameters: BreedingSitesApiGeoListRequest = {}, options?: RawAxiosRequestConfig) {
        return BreedingSitesApiFp(this.configuration).geoList(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasLarvae, requestParameters.hasNearMosquitoes, requestParameters.hasPhotos, requestParameters.hasWater, requestParameters.orderBy, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.siteType, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BreedingSitesApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public list(requestParameters: BreedingSitesApiListRequest = {}, options?: RawAxiosRequestConfig) {
        return BreedingSitesApiFp(this.configuration).list(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasLarvae, requestParameters.hasNearMosquitoes, requestParameters.hasPhotos, requestParameters.hasWater, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.siteType, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Current User\'s Breeding Sites
     * @param {BreedingSitesApiListMineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMine(requestParameters: BreedingSitesApiListMineRequest = {}, options?: RawAxiosRequestConfig) {
        return BreedingSitesApiFp(this.configuration).listMine(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasLarvae, requestParameters.hasNearMosquitoes, requestParameters.hasPhotos, requestParameters.hasWater, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.siteType, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BreedingSitesApiRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieve(requestParameters: BreedingSitesApiRetrieveRequest, options?: RawAxiosRequestConfig) {
        return BreedingSitesApiFp(this.configuration).retrieve(requestParameters.uuid, options).then((request) => request(this.axios, this.basePath));
    }
}

