/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BiteEventEnvironment } from '../models';
// @ts-ignore
import type { BiteEventMoment } from '../models';
// @ts-ignore
import type { BitesListFormatParameter } from '../models';
// @ts-ignore
import type { BitesListOrderByParameter } from '../models';
// @ts-ignore
import type { ErrorResponse401 } from '../models';
// @ts-ignore
import type { ErrorResponse403 } from '../models';
// @ts-ignore
import type { ErrorResponse404 } from '../models';
// @ts-ignore
import type { LocationRequest } from '../models';
// @ts-ignore
import type { MosquitoAppearanceRequest } from '../models';
// @ts-ignore
import type { Observation } from '../models';
// @ts-ignore
import type { ObservationGeoJsonModelList } from '../models';
// @ts-ignore
import type { ObservationGeoModel } from '../models';
// @ts-ignore
import type { ObservationsCreateValidationError } from '../models';
// @ts-ignore
import type { ObservationsGeoListValidationError } from '../models';
// @ts-ignore
import type { ObservationsListMineIdentificationTaxonIdsLookupParameter } from '../models';
// @ts-ignore
import type { ObservationsListMineValidationError } from '../models';
// @ts-ignore
import type { ObservationsListValidationError } from '../models';
// @ts-ignore
import type { PaginatedObservationList } from '../models';
/**
 * ObservationsApi - axios parameter creator
 */
export const ObservationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} createdAt 
         * @param {string} sentAt 
         * @param {LocationRequest} location 
         * @param {Array<File>} photos 
         * @param {string | null} [note] 
         * @param {Array<string>} [tags] 
         * @param {BiteEventEnvironment | null} [eventEnvironment] 
         * @param {BiteEventMoment | null} [eventMoment] 
         * @param {MosquitoAppearanceRequest | null} [mosquitoAppearance] User-provided description of the mosquito\\\&#39;s appearance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createdAt: string, sentAt: string, location: LocationRequest, photos: Array<File>, note?: string | null, tags?: Array<string>, eventEnvironment?: BiteEventEnvironment | null, eventMoment?: BiteEventMoment | null, mosquitoAppearance?: MosquitoAppearanceRequest | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createdAt' is not null or undefined
            assertParamExists('create', 'createdAt', createdAt)
            // verify required parameter 'sentAt' is not null or undefined
            assertParamExists('create', 'sentAt', sentAt)
            // verify required parameter 'location' is not null or undefined
            assertParamExists('create', 'location', location)
            // verify required parameter 'photos' is not null or undefined
            assertParamExists('create', 'photos', photos)
            const localVarPath = `/observations/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (createdAt !== undefined) { 
                localVarFormParams.append('created_at', createdAt as any);
            }

            if (sentAt !== undefined) { 
                localVarFormParams.append('sent_at', sentAt as any);
            }

            if (location !== undefined) { 
                localVarFormParams.append('location', new Blob([JSON.stringify(location, replaceWithSerializableTypeIfNeeded)], { type: "application/json", }));
            }

            if (note !== undefined) { 
                localVarFormParams.append('note', note as any);
            }
            if (tags) {
                localVarFormParams.append('tags', tags.join(COLLECTION_FORMATS.csv));
            }

            if (photos) {
                photos.forEach((element) => {
                    localVarFormParams.append('photos', element as any);
                })
            }


            if (eventEnvironment !== undefined) { 
                localVarFormParams.append('event_environment', eventEnvironment as any);
            }

            if (eventMoment !== undefined) { 
                localVarFormParams.append('event_moment', eventMoment as any);
            }

            if (mosquitoAppearance !== undefined) { 
                localVarFormParams.append('mosquito_appearance', new Blob([JSON.stringify(mosquitoAppearance, replaceWithSerializableTypeIfNeeded)], { type: "application/json", }));
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        destroy: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('destroy', 'uuid', uuid)
            const localVarPath = `/observations/{uuid}/`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasPhotos] Has any photo
         * @param {Array<string>} [identificationTaxonIds] 
         * @param {ObservationsListMineIdentificationTaxonIdsLookupParameter} [identificationTaxonIdsLookup] 
         * @param {boolean} [negateIdentificationTaxonIds] Negate identification_taxon_ids filter
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geoList: async (boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, geoPrecision?: number, hasPhotos?: boolean, identificationTaxonIds?: Array<string>, identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter, negateIdentificationTaxonIds?: boolean, orderBy?: Array<BitesListOrderByParameter>, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/observations/geo/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (boundaryUuid !== undefined) {
                localVarQueryParameter['boundary_uuid'] = boundaryUuid;
            }

            if (countryId !== undefined) {
                localVarQueryParameter['country_id'] = countryId;
            }

            if (createdAtAfter !== undefined) {
                localVarQueryParameter['created_at_after'] = (createdAtAfter as any instanceof Date) ?
                    (createdAtAfter as any).toISOString() :
                    createdAtAfter;
            }

            if (createdAtBefore !== undefined) {
                localVarQueryParameter['created_at_before'] = (createdAtBefore as any instanceof Date) ?
                    (createdAtBefore as any).toISOString() :
                    createdAtBefore;
            }

            if (dist !== undefined) {
                localVarQueryParameter['dist'] = dist;
            }

            if (geoPrecision !== undefined) {
                localVarQueryParameter['geo_precision'] = geoPrecision;
            }

            if (hasPhotos !== undefined) {
                localVarQueryParameter['has_photos'] = hasPhotos;
            }

            if (identificationTaxonIds) {
                localVarQueryParameter['identification_taxon_ids'] = identificationTaxonIds;
            }

            if (identificationTaxonIdsLookup !== undefined) {
                localVarQueryParameter['identification_taxon_ids_lookup'] = identificationTaxonIdsLookup;
            }

            if (negateIdentificationTaxonIds !== undefined) {
                localVarQueryParameter['negate_identification_taxon_ids'] = negateIdentificationTaxonIds;
            }

            if (orderBy) {
                localVarQueryParameter['order_by'] = orderBy.join(COLLECTION_FORMATS.csv);
            }

            if (point) {
                localVarQueryParameter['point'] = point.join(COLLECTION_FORMATS.csv);
            }

            if (receivedAtAfter !== undefined) {
                localVarQueryParameter['received_at_after'] = (receivedAtAfter as any instanceof Date) ?
                    (receivedAtAfter as any).toISOString() :
                    receivedAtAfter;
            }

            if (receivedAtBefore !== undefined) {
                localVarQueryParameter['received_at_before'] = (receivedAtBefore as any instanceof Date) ?
                    (receivedAtBefore as any).toISOString() :
                    receivedAtBefore;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (shortId !== undefined) {
                localVarQueryParameter['short_id'] = shortId;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (updatedAtAfter !== undefined) {
                localVarQueryParameter['updated_at_after'] = (updatedAtAfter as any instanceof Date) ?
                    (updatedAtAfter as any).toISOString() :
                    updatedAtAfter;
            }

            if (updatedAtBefore !== undefined) {
                localVarQueryParameter['updated_at_before'] = (updatedAtBefore as any instanceof Date) ?
                    (updatedAtBefore as any).toISOString() :
                    updatedAtBefore;
            }

            if (userUuid !== undefined) {
                localVarQueryParameter['user_uuid'] = userUuid;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/geo+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasPhotos] Has any photo
         * @param {Array<string>} [identificationTaxonIds] 
         * @param {ObservationsListMineIdentificationTaxonIdsLookupParameter} [identificationTaxonIdsLookup] 
         * @param {boolean} [negateIdentificationTaxonIds] Negate identification_taxon_ids filter
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasPhotos?: boolean, identificationTaxonIds?: Array<string>, identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter, negateIdentificationTaxonIds?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/observations/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (boundaryUuid !== undefined) {
                localVarQueryParameter['boundary_uuid'] = boundaryUuid;
            }

            if (countryId !== undefined) {
                localVarQueryParameter['country_id'] = countryId;
            }

            if (createdAtAfter !== undefined) {
                localVarQueryParameter['created_at_after'] = (createdAtAfter as any instanceof Date) ?
                    (createdAtAfter as any).toISOString() :
                    createdAtAfter;
            }

            if (createdAtBefore !== undefined) {
                localVarQueryParameter['created_at_before'] = (createdAtBefore as any instanceof Date) ?
                    (createdAtBefore as any).toISOString() :
                    createdAtBefore;
            }

            if (dist !== undefined) {
                localVarQueryParameter['dist'] = dist;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (geoPrecision !== undefined) {
                localVarQueryParameter['geo_precision'] = geoPrecision;
            }

            if (hasPhotos !== undefined) {
                localVarQueryParameter['has_photos'] = hasPhotos;
            }

            if (identificationTaxonIds) {
                localVarQueryParameter['identification_taxon_ids'] = identificationTaxonIds;
            }

            if (identificationTaxonIdsLookup !== undefined) {
                localVarQueryParameter['identification_taxon_ids_lookup'] = identificationTaxonIdsLookup;
            }

            if (negateIdentificationTaxonIds !== undefined) {
                localVarQueryParameter['negate_identification_taxon_ids'] = negateIdentificationTaxonIds;
            }

            if (orderBy) {
                localVarQueryParameter['order_by'] = orderBy.join(COLLECTION_FORMATS.csv);
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (point) {
                localVarQueryParameter['point'] = point.join(COLLECTION_FORMATS.csv);
            }

            if (receivedAtAfter !== undefined) {
                localVarQueryParameter['received_at_after'] = (receivedAtAfter as any instanceof Date) ?
                    (receivedAtAfter as any).toISOString() :
                    receivedAtAfter;
            }

            if (receivedAtBefore !== undefined) {
                localVarQueryParameter['received_at_before'] = (receivedAtBefore as any instanceof Date) ?
                    (receivedAtBefore as any).toISOString() :
                    receivedAtBefore;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (shortId !== undefined) {
                localVarQueryParameter['short_id'] = shortId;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (updatedAtAfter !== undefined) {
                localVarQueryParameter['updated_at_after'] = (updatedAtAfter as any instanceof Date) ?
                    (updatedAtAfter as any).toISOString() :
                    updatedAtAfter;
            }

            if (updatedAtBefore !== undefined) {
                localVarQueryParameter['updated_at_before'] = (updatedAtBefore as any instanceof Date) ?
                    (updatedAtBefore as any).toISOString() :
                    updatedAtBefore;
            }

            if (userUuid !== undefined) {
                localVarQueryParameter['user_uuid'] = userUuid;
            }

            localVarHeaderParameter['Accept'] = 'application/json,text/csv';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Current User\'s Observations
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasPhotos] Has any photo
         * @param {Array<string>} [identificationTaxonIds] 
         * @param {ObservationsListMineIdentificationTaxonIdsLookupParameter} [identificationTaxonIdsLookup] 
         * @param {boolean} [negateIdentificationTaxonIds] Negate identification_taxon_ids filter
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMine: async (boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasPhotos?: boolean, identificationTaxonIds?: Array<string>, identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter, negateIdentificationTaxonIds?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/me/observations/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (boundaryUuid !== undefined) {
                localVarQueryParameter['boundary_uuid'] = boundaryUuid;
            }

            if (countryId !== undefined) {
                localVarQueryParameter['country_id'] = countryId;
            }

            if (createdAtAfter !== undefined) {
                localVarQueryParameter['created_at_after'] = (createdAtAfter as any instanceof Date) ?
                    (createdAtAfter as any).toISOString() :
                    createdAtAfter;
            }

            if (createdAtBefore !== undefined) {
                localVarQueryParameter['created_at_before'] = (createdAtBefore as any instanceof Date) ?
                    (createdAtBefore as any).toISOString() :
                    createdAtBefore;
            }

            if (dist !== undefined) {
                localVarQueryParameter['dist'] = dist;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (geoPrecision !== undefined) {
                localVarQueryParameter['geo_precision'] = geoPrecision;
            }

            if (hasPhotos !== undefined) {
                localVarQueryParameter['has_photos'] = hasPhotos;
            }

            if (identificationTaxonIds) {
                localVarQueryParameter['identification_taxon_ids'] = identificationTaxonIds;
            }

            if (identificationTaxonIdsLookup !== undefined) {
                localVarQueryParameter['identification_taxon_ids_lookup'] = identificationTaxonIdsLookup;
            }

            if (negateIdentificationTaxonIds !== undefined) {
                localVarQueryParameter['negate_identification_taxon_ids'] = negateIdentificationTaxonIds;
            }

            if (orderBy) {
                localVarQueryParameter['order_by'] = orderBy.join(COLLECTION_FORMATS.csv);
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (point) {
                localVarQueryParameter['point'] = point.join(COLLECTION_FORMATS.csv);
            }

            if (receivedAtAfter !== undefined) {
                localVarQueryParameter['received_at_after'] = (receivedAtAfter as any instanceof Date) ?
                    (receivedAtAfter as any).toISOString() :
                    receivedAtAfter;
            }

            if (receivedAtBefore !== undefined) {
                localVarQueryParameter['received_at_before'] = (receivedAtBefore as any instanceof Date) ?
                    (receivedAtBefore as any).toISOString() :
                    receivedAtBefore;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (shortId !== undefined) {
                localVarQueryParameter['short_id'] = shortId;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (updatedAtAfter !== undefined) {
                localVarQueryParameter['updated_at_after'] = (updatedAtAfter as any instanceof Date) ?
                    (updatedAtAfter as any).toISOString() :
                    updatedAtAfter;
            }

            if (updatedAtBefore !== undefined) {
                localVarQueryParameter['updated_at_before'] = (updatedAtBefore as any instanceof Date) ?
                    (updatedAtBefore as any).toISOString() :
                    updatedAtBefore;
            }

            if (userUuid !== undefined) {
                localVarQueryParameter['user_uuid'] = userUuid;
            }

            localVarHeaderParameter['Accept'] = 'application/json,text/csv';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieve: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('retrieve', 'uuid', uuid)
            const localVarPath = `/observations/{uuid}/`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ObservationsApi - functional programming interface
 */
export const ObservationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ObservationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} createdAt 
         * @param {string} sentAt 
         * @param {LocationRequest} location 
         * @param {Array<File>} photos 
         * @param {string | null} [note] 
         * @param {Array<string>} [tags] 
         * @param {BiteEventEnvironment | null} [eventEnvironment] 
         * @param {BiteEventMoment | null} [eventMoment] 
         * @param {MosquitoAppearanceRequest | null} [mosquitoAppearance] User-provided description of the mosquito\\\&#39;s appearance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createdAt: string, sentAt: string, location: LocationRequest, photos: Array<File>, note?: string | null, tags?: Array<string>, eventEnvironment?: BiteEventEnvironment | null, eventMoment?: BiteEventMoment | null, mosquitoAppearance?: MosquitoAppearanceRequest | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Observation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createdAt, sentAt, location, photos, note, tags, eventEnvironment, eventMoment, mosquitoAppearance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservationsApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async destroy(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.destroy(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservationsApi.destroy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasPhotos] Has any photo
         * @param {Array<string>} [identificationTaxonIds] 
         * @param {ObservationsListMineIdentificationTaxonIdsLookupParameter} [identificationTaxonIdsLookup] 
         * @param {boolean} [negateIdentificationTaxonIds] Negate identification_taxon_ids filter
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geoList(boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, geoPrecision?: number, hasPhotos?: boolean, identificationTaxonIds?: Array<string>, identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter, negateIdentificationTaxonIds?: boolean, orderBy?: Array<BitesListOrderByParameter>, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ObservationGeoModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geoList(boundaryUuid, countryId, createdAtAfter, createdAtBefore, dist, geoPrecision, hasPhotos, identificationTaxonIds, identificationTaxonIdsLookup, negateIdentificationTaxonIds, orderBy, point, receivedAtAfter, receivedAtBefore, search, shortId, tags, updatedAtAfter, updatedAtBefore, userUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservationsApi.geoList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasPhotos] Has any photo
         * @param {Array<string>} [identificationTaxonIds] 
         * @param {ObservationsListMineIdentificationTaxonIdsLookupParameter} [identificationTaxonIdsLookup] 
         * @param {boolean} [negateIdentificationTaxonIds] Negate identification_taxon_ids filter
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasPhotos?: boolean, identificationTaxonIds?: Array<string>, identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter, negateIdentificationTaxonIds?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedObservationList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(boundaryUuid, countryId, createdAtAfter, createdAtBefore, dist, format, geoPrecision, hasPhotos, identificationTaxonIds, identificationTaxonIdsLookup, negateIdentificationTaxonIds, orderBy, page, pageSize, point, receivedAtAfter, receivedAtBefore, search, shortId, tags, updatedAtAfter, updatedAtBefore, userUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservationsApi.list']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Current User\'s Observations
         * @param {string} [boundaryUuid] 
         * @param {number} [countryId] 
         * @param {string} [createdAtAfter] Created at
         * @param {string} [createdAtBefore] Created at
         * @param {number} [dist] Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
         * @param {BitesListFormatParameter} [format] 
         * @param {number} [geoPrecision] Latitude/Longitude precision
         * @param {boolean} [hasPhotos] Has any photo
         * @param {Array<string>} [identificationTaxonIds] 
         * @param {ObservationsListMineIdentificationTaxonIdsLookupParameter} [identificationTaxonIdsLookup] 
         * @param {boolean} [negateIdentificationTaxonIds] Negate identification_taxon_ids filter
         * @param {Array<BitesListOrderByParameter>} [orderBy] Ordenamiento  
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<number>} [point] Point represented in **x,y** format. Represents **point** in **Distance to point filter**
         * @param {string} [receivedAtAfter] Received at
         * @param {string} [receivedAtBefore] Received at
         * @param {string} [search] Un término de búsqueda.
         * @param {string} [shortId] Short ID
         * @param {Array<string>} [tags] Múltiples valores separados por comas.
         * @param {string} [updatedAtAfter] Update at
         * @param {string} [updatedAtBefore] Update at
         * @param {string} [userUuid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMine(boundaryUuid?: string, countryId?: number, createdAtAfter?: string, createdAtBefore?: string, dist?: number, format?: BitesListFormatParameter, geoPrecision?: number, hasPhotos?: boolean, identificationTaxonIds?: Array<string>, identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter, negateIdentificationTaxonIds?: boolean, orderBy?: Array<BitesListOrderByParameter>, page?: number, pageSize?: number, point?: Array<number>, receivedAtAfter?: string, receivedAtBefore?: string, search?: string, shortId?: string, tags?: Array<string>, updatedAtAfter?: string, updatedAtBefore?: string, userUuid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedObservationList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMine(boundaryUuid, countryId, createdAtAfter, createdAtBefore, dist, format, geoPrecision, hasPhotos, identificationTaxonIds, identificationTaxonIdsLookup, negateIdentificationTaxonIds, orderBy, page, pageSize, point, receivedAtAfter, receivedAtBefore, search, shortId, tags, updatedAtAfter, updatedAtBefore, userUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservationsApi.listMine']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieve(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Observation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieve(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservationsApi.retrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ObservationsApi - factory interface
 */
export const ObservationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ObservationsApiFp(configuration)
    return {
        /**
         * 
         * @param {ObservationsApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(requestParameters: ObservationsApiCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Observation> {
            return localVarFp.create(requestParameters.createdAt, requestParameters.sentAt, requestParameters.location, requestParameters.photos, requestParameters.note, requestParameters.tags, requestParameters.eventEnvironment, requestParameters.eventMoment, requestParameters.mosquitoAppearance, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ObservationsApiDestroyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        destroy(requestParameters: ObservationsApiDestroyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.destroy(requestParameters.uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ObservationsApiGeoListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geoList(requestParameters: ObservationsApiGeoListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<ObservationGeoModel>> {
            return localVarFp.geoList(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.geoPrecision, requestParameters.hasPhotos, requestParameters.identificationTaxonIds, requestParameters.identificationTaxonIdsLookup, requestParameters.negateIdentificationTaxonIds, requestParameters.orderBy, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ObservationsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: ObservationsApiListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedObservationList> {
            return localVarFp.list(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasPhotos, requestParameters.identificationTaxonIds, requestParameters.identificationTaxonIdsLookup, requestParameters.negateIdentificationTaxonIds, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Current User\'s Observations
         * @param {ObservationsApiListMineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMine(requestParameters: ObservationsApiListMineRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedObservationList> {
            return localVarFp.listMine(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasPhotos, requestParameters.identificationTaxonIds, requestParameters.identificationTaxonIdsLookup, requestParameters.negateIdentificationTaxonIds, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ObservationsApiRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieve(requestParameters: ObservationsApiRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<Observation> {
            return localVarFp.retrieve(requestParameters.uuid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for create operation in ObservationsApi.
 */
export interface ObservationsApiCreateRequest {
    readonly createdAt: string

    readonly sentAt: string

    readonly location: LocationRequest

    readonly photos: Array<File>

    readonly note?: string | null

    readonly tags?: Array<string>

    readonly eventEnvironment?: BiteEventEnvironment | null

    readonly eventMoment?: BiteEventMoment | null

    /**
     * User-provided description of the mosquito\\\&#39;s appearance
     */
    readonly mosquitoAppearance?: MosquitoAppearanceRequest | null
}

/**
 * Request parameters for destroy operation in ObservationsApi.
 */
export interface ObservationsApiDestroyRequest {
    readonly uuid: string
}

/**
 * Request parameters for geoList operation in ObservationsApi.
 */
export interface ObservationsApiGeoListRequest {
    readonly boundaryUuid?: string

    readonly countryId?: number

    /**
     * Created at
     */
    readonly createdAtAfter?: string

    /**
     * Created at
     */
    readonly createdAtBefore?: string

    /**
     * Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
     */
    readonly dist?: number

    /**
     * Latitude/Longitude precision
     */
    readonly geoPrecision?: number

    /**
     * Has any photo
     */
    readonly hasPhotos?: boolean

    readonly identificationTaxonIds?: Array<string>

    readonly identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter

    /**
     * Negate identification_taxon_ids filter
     */
    readonly negateIdentificationTaxonIds?: boolean

    /**
     * Ordenamiento  
     */
    readonly orderBy?: Array<BitesListOrderByParameter>

    /**
     * Point represented in **x,y** format. Represents **point** in **Distance to point filter**
     */
    readonly point?: Array<number>

    /**
     * Received at
     */
    readonly receivedAtAfter?: string

    /**
     * Received at
     */
    readonly receivedAtBefore?: string

    /**
     * Un término de búsqueda.
     */
    readonly search?: string

    /**
     * Short ID
     */
    readonly shortId?: string

    /**
     * Múltiples valores separados por comas.
     */
    readonly tags?: Array<string>

    /**
     * Update at
     */
    readonly updatedAtAfter?: string

    /**
     * Update at
     */
    readonly updatedAtBefore?: string

    readonly userUuid?: string
}

/**
 * Request parameters for list operation in ObservationsApi.
 */
export interface ObservationsApiListRequest {
    readonly boundaryUuid?: string

    readonly countryId?: number

    /**
     * Created at
     */
    readonly createdAtAfter?: string

    /**
     * Created at
     */
    readonly createdAtBefore?: string

    /**
     * Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
     */
    readonly dist?: number

    readonly format?: BitesListFormatParameter

    /**
     * Latitude/Longitude precision
     */
    readonly geoPrecision?: number

    /**
     * Has any photo
     */
    readonly hasPhotos?: boolean

    readonly identificationTaxonIds?: Array<string>

    readonly identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter

    /**
     * Negate identification_taxon_ids filter
     */
    readonly negateIdentificationTaxonIds?: boolean

    /**
     * Ordenamiento  
     */
    readonly orderBy?: Array<BitesListOrderByParameter>

    /**
     * Un número de página dentro del conjunto de resultados paginado.
     */
    readonly page?: number

    /**
     * Número de resultados a devolver por página.
     */
    readonly pageSize?: number

    /**
     * Point represented in **x,y** format. Represents **point** in **Distance to point filter**
     */
    readonly point?: Array<number>

    /**
     * Received at
     */
    readonly receivedAtAfter?: string

    /**
     * Received at
     */
    readonly receivedAtBefore?: string

    /**
     * Un término de búsqueda.
     */
    readonly search?: string

    /**
     * Short ID
     */
    readonly shortId?: string

    /**
     * Múltiples valores separados por comas.
     */
    readonly tags?: Array<string>

    /**
     * Update at
     */
    readonly updatedAtAfter?: string

    /**
     * Update at
     */
    readonly updatedAtBefore?: string

    readonly userUuid?: string
}

/**
 * Request parameters for listMine operation in ObservationsApi.
 */
export interface ObservationsApiListMineRequest {
    readonly boundaryUuid?: string

    readonly countryId?: number

    /**
     * Created at
     */
    readonly createdAtAfter?: string

    /**
     * Created at
     */
    readonly createdAtBefore?: string

    /**
     * Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed.
     */
    readonly dist?: number

    readonly format?: BitesListFormatParameter

    /**
     * Latitude/Longitude precision
     */
    readonly geoPrecision?: number

    /**
     * Has any photo
     */
    readonly hasPhotos?: boolean

    readonly identificationTaxonIds?: Array<string>

    readonly identificationTaxonIdsLookup?: ObservationsListMineIdentificationTaxonIdsLookupParameter

    /**
     * Negate identification_taxon_ids filter
     */
    readonly negateIdentificationTaxonIds?: boolean

    /**
     * Ordenamiento  
     */
    readonly orderBy?: Array<BitesListOrderByParameter>

    /**
     * Un número de página dentro del conjunto de resultados paginado.
     */
    readonly page?: number

    /**
     * Número de resultados a devolver por página.
     */
    readonly pageSize?: number

    /**
     * Point represented in **x,y** format. Represents **point** in **Distance to point filter**
     */
    readonly point?: Array<number>

    /**
     * Received at
     */
    readonly receivedAtAfter?: string

    /**
     * Received at
     */
    readonly receivedAtBefore?: string

    /**
     * Un término de búsqueda.
     */
    readonly search?: string

    /**
     * Short ID
     */
    readonly shortId?: string

    /**
     * Múltiples valores separados por comas.
     */
    readonly tags?: Array<string>

    /**
     * Update at
     */
    readonly updatedAtAfter?: string

    /**
     * Update at
     */
    readonly updatedAtBefore?: string

    readonly userUuid?: string
}

/**
 * Request parameters for retrieve operation in ObservationsApi.
 */
export interface ObservationsApiRetrieveRequest {
    readonly uuid: string
}

/**
 * ObservationsApi - object-oriented interface
 */
export class ObservationsApi extends BaseAPI {
    /**
     * 
     * @param {ObservationsApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(requestParameters: ObservationsApiCreateRequest, options?: RawAxiosRequestConfig) {
        return ObservationsApiFp(this.configuration).create(requestParameters.createdAt, requestParameters.sentAt, requestParameters.location, requestParameters.photos, requestParameters.note, requestParameters.tags, requestParameters.eventEnvironment, requestParameters.eventMoment, requestParameters.mosquitoAppearance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ObservationsApiDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public destroy(requestParameters: ObservationsApiDestroyRequest, options?: RawAxiosRequestConfig) {
        return ObservationsApiFp(this.configuration).destroy(requestParameters.uuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ObservationsApiGeoListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public geoList(requestParameters: ObservationsApiGeoListRequest = {}, options?: RawAxiosRequestConfig) {
        return ObservationsApiFp(this.configuration).geoList(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.geoPrecision, requestParameters.hasPhotos, requestParameters.identificationTaxonIds, requestParameters.identificationTaxonIdsLookup, requestParameters.negateIdentificationTaxonIds, requestParameters.orderBy, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ObservationsApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public list(requestParameters: ObservationsApiListRequest = {}, options?: RawAxiosRequestConfig) {
        return ObservationsApiFp(this.configuration).list(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasPhotos, requestParameters.identificationTaxonIds, requestParameters.identificationTaxonIdsLookup, requestParameters.negateIdentificationTaxonIds, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Current User\'s Observations
     * @param {ObservationsApiListMineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMine(requestParameters: ObservationsApiListMineRequest = {}, options?: RawAxiosRequestConfig) {
        return ObservationsApiFp(this.configuration).listMine(requestParameters.boundaryUuid, requestParameters.countryId, requestParameters.createdAtAfter, requestParameters.createdAtBefore, requestParameters.dist, requestParameters.format, requestParameters.geoPrecision, requestParameters.hasPhotos, requestParameters.identificationTaxonIds, requestParameters.identificationTaxonIdsLookup, requestParameters.negateIdentificationTaxonIds, requestParameters.orderBy, requestParameters.page, requestParameters.pageSize, requestParameters.point, requestParameters.receivedAtAfter, requestParameters.receivedAtBefore, requestParameters.search, requestParameters.shortId, requestParameters.tags, requestParameters.updatedAtAfter, requestParameters.updatedAtBefore, requestParameters.userUuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ObservationsApiRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieve(requestParameters: ObservationsApiRetrieveRequest, options?: RawAxiosRequestConfig) {
        return ObservationsApiFp(this.configuration).retrieve(requestParameters.uuid, options).then((request) => request(this.axios, this.basePath));
    }
}

