/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse401 } from '../models';
// @ts-ignore
import type { ErrorResponse403 } from '../models';
// @ts-ignore
import type { ErrorResponse404 } from '../models';
// @ts-ignore
import type { PaginatedTaxonList } from '../models';
// @ts-ignore
import type { TaxaListRankParameter } from '../models';
// @ts-ignore
import type { TaxaListValidationError } from '../models';
// @ts-ignore
import type { Taxon } from '../models';
// @ts-ignore
import type { TaxonTreeNode } from '../models';
/**
 * TaxaApi - axios parameter creator
 */
export const TaxaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {boolean} [isRelevant] 
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<TaxaListRankParameter>} [rank] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (isRelevant?: boolean, page?: number, pageSize?: number, rank?: Array<TaxaListRankParameter>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/taxa/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (isRelevant !== undefined) {
                localVarQueryParameter['is_relevant'] = isRelevant;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (rank) {
                localVarQueryParameter['rank'] = rank;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Un valor de entero único que identifique este taxon.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieve: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('retrieve', 'id', id)
            const localVarPath = `/taxa/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootTreeRetrieve: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/taxa/tree/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Un valor de entero único que identifique este taxon.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        treeRetrieve: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('treeRetrieve', 'id', id)
            const localVarPath = `/taxa/{id}/tree/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication cookieAuth required

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaxaApi - functional programming interface
 */
export const TaxaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaxaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {boolean} [isRelevant] 
         * @param {number} [page] Un número de página dentro del conjunto de resultados paginado.
         * @param {number} [pageSize] Número de resultados a devolver por página.
         * @param {Array<TaxaListRankParameter>} [rank] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(isRelevant?: boolean, page?: number, pageSize?: number, rank?: Array<TaxaListRankParameter>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedTaxonList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(isRelevant, page, pageSize, rank, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaxaApi.list']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id Un valor de entero único que identifique este taxon.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieve(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Taxon>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieve(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaxaApi.retrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootTreeRetrieve(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaxonTreeNode>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootTreeRetrieve(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaxaApi.rootTreeRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id Un valor de entero único que identifique este taxon.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async treeRetrieve(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaxonTreeNode>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.treeRetrieve(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaxaApi.treeRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TaxaApi - factory interface
 */
export const TaxaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaxaApiFp(configuration)
    return {
        /**
         * 
         * @param {TaxaApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: TaxaApiListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedTaxonList> {
            return localVarFp.list(requestParameters.isRelevant, requestParameters.page, requestParameters.pageSize, requestParameters.rank, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TaxaApiRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieve(requestParameters: TaxaApiRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<Taxon> {
            return localVarFp.retrieve(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootTreeRetrieve(options?: RawAxiosRequestConfig): AxiosPromise<TaxonTreeNode> {
            return localVarFp.rootTreeRetrieve(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TaxaApiTreeRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        treeRetrieve(requestParameters: TaxaApiTreeRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaxonTreeNode> {
            return localVarFp.treeRetrieve(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for list operation in TaxaApi.
 */
export interface TaxaApiListRequest {
    readonly isRelevant?: boolean

    /**
     * Un número de página dentro del conjunto de resultados paginado.
     */
    readonly page?: number

    /**
     * Número de resultados a devolver por página.
     */
    readonly pageSize?: number

    readonly rank?: Array<TaxaListRankParameter>
}

/**
 * Request parameters for retrieve operation in TaxaApi.
 */
export interface TaxaApiRetrieveRequest {
    /**
     * Un valor de entero único que identifique este taxon.
     */
    readonly id: number
}

/**
 * Request parameters for treeRetrieve operation in TaxaApi.
 */
export interface TaxaApiTreeRetrieveRequest {
    /**
     * Un valor de entero único que identifique este taxon.
     */
    readonly id: number
}

/**
 * TaxaApi - object-oriented interface
 */
export class TaxaApi extends BaseAPI {
    /**
     * 
     * @param {TaxaApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public list(requestParameters: TaxaApiListRequest = {}, options?: RawAxiosRequestConfig) {
        return TaxaApiFp(this.configuration).list(requestParameters.isRelevant, requestParameters.page, requestParameters.pageSize, requestParameters.rank, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TaxaApiRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieve(requestParameters: TaxaApiRetrieveRequest, options?: RawAxiosRequestConfig) {
        return TaxaApiFp(this.configuration).retrieve(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rootTreeRetrieve(options?: RawAxiosRequestConfig) {
        return TaxaApiFp(this.configuration).rootTreeRetrieve(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TaxaApiTreeRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public treeRetrieve(requestParameters: TaxaApiTreeRetrieveRequest, options?: RawAxiosRequestConfig) {
        return TaxaApiFp(this.configuration).treeRetrieve(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

