/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AnnotationClassification } from './annotation-classification';
// May contain unused imports in some cases
// @ts-ignore
import type { AnnotationFeedback } from './annotation-feedback';
// May contain unused imports in some cases
// @ts-ignore
import type { AnnotationType } from './annotation-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SimpleAnnotatorUser } from './simple-annotator-user';
// May contain unused imports in some cases
// @ts-ignore
import type { SimplePhoto } from './simple-photo';

/**
 * 
 * @export
 * @interface Annotation
 */
export interface Annotation {
    /**
     * 
     * @type {number}
     * @memberof Annotation
     */
    'id': number;
    /**
     * UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).
     * @type {string}
     * @memberof Annotation
     */
    'observation_uuid': string;
    /**
     * 
     * @type {SimpleAnnotatorUser}
     * @memberof Annotation
     */
    'user': SimpleAnnotatorUser;
    /**
     * 
     * @type {SimplePhoto}
     * @memberof Annotation
     */
    'best_photo': SimplePhoto | null;
    /**
     * 
     * @type {AnnotationClassification}
     * @memberof Annotation
     */
    'classification': AnnotationClassification | null;
    /**
     * 
     * @type {AnnotationFeedback}
     * @memberof Annotation
     */
    'feedback'?: AnnotationFeedback;
    /**
     * 
     * @type {AnnotationType}
     * @memberof Annotation
     */
    'type': AnnotationType;
    /**
     * 
     * @type {boolean}
     * @memberof Annotation
     */
    'is_flagged': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Annotation
     */
    'is_decisive': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Annotation
     */
    'is_favourite': boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Annotation
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Annotation
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Annotation
     */
    'updated_at': string;
}



