/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SimplePhoto } from './simple-photo';
// May contain unused imports in some cases
// @ts-ignore
import type { SimpleUser } from './simple-user';
// May contain unused imports in some cases
// @ts-ignore
import type { SimplifiedLocation } from './simplified-location';

/**
 * 
 * @export
 * @interface AssignedObservation
 */
export interface AssignedObservation {
    /**
     * 
     * @type {string}
     * @memberof AssignedObservation
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof AssignedObservation
     */
    'created_at': string;
    /**
     * The date and time when the record was created, displayed in the local timezone specified for this entry.
     * @type {string}
     * @memberof AssignedObservation
     */
    'created_at_local': string;
    /**
     * 
     * @type {string}
     * @memberof AssignedObservation
     */
    'received_at': string;
    /**
     * 
     * @type {SimplifiedLocation}
     * @memberof AssignedObservation
     */
    'location': SimplifiedLocation;
    /**
     * Note user attached to report.
     * @type {string}
     * @memberof AssignedObservation
     */
    'note'?: string | null;
    /**
     * 
     * @type {Array<SimplePhoto>}
     * @memberof AssignedObservation
     */
    'photos': Array<SimplePhoto>;
    /**
     * 
     * @type {SimpleUser}
     * @memberof AssignedObservation
     */
    'user': SimpleUser;
}

