/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssignmentAnnotationType } from './assignment-annotation-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SimplifiedObservationWithPhotos } from './simplified-observation-with-photos';

/**
 * 
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * 
     * @type {SimplifiedObservationWithPhotos}
     * @memberof Assignment
     */
    'observation': SimplifiedObservationWithPhotos;
    /**
     * 
     * @type {AssignmentAnnotationType}
     * @memberof Assignment
     */
    'annotation_type': AssignmentAnnotationType;
}



