/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthChangePasswordPasswordErrorComponentAttr } from './auth-change-password-password-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthChangePasswordPasswordErrorComponentCode } from './auth-change-password-password-error-component-code';

/**
 * 
 * @export
 * @interface AuthChangePasswordPasswordErrorComponent
 */
export interface AuthChangePasswordPasswordErrorComponent {
    /**
     * 
     * @type {AuthChangePasswordPasswordErrorComponentAttr}
     * @memberof AuthChangePasswordPasswordErrorComponent
     */
    'attr': AuthChangePasswordPasswordErrorComponentAttr;
    /**
     * 
     * @type {AuthChangePasswordPasswordErrorComponentCode}
     * @memberof AuthChangePasswordPasswordErrorComponent
     */
    'code': AuthChangePasswordPasswordErrorComponentCode;
    /**
     * 
     * @type {string}
     * @memberof AuthChangePasswordPasswordErrorComponent
     */
    'detail': string;
}



