/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListBoundaryUuidErrorComponent } from './bites-geo-list-boundary-uuid-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListBoundaryUuidErrorComponentAttr } from './bites-geo-list-boundary-uuid-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListBoundaryUuidErrorComponentCode } from './bites-geo-list-boundary-uuid-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListCountryIdErrorComponent } from './bites-geo-list-country-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListCreatedAtErrorComponent } from './bites-geo-list-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListGeoPrecisionErrorComponent } from './bites-geo-list-geo-precision-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListOrderByErrorComponent } from './bites-geo-list-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListReceivedAtErrorComponent } from './bites-geo-list-received-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListShortIdErrorComponent } from './bites-geo-list-short-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListTagsErrorComponent } from './bites-geo-list-tags-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListUpdatedAtErrorComponent } from './bites-geo-list-updated-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesGeoListUserUuidErrorComponent } from './bites-geo-list-user-uuid-error-component';

/**
 * @type BitesGeoListError
 */
export type BitesGeoListError = { attr: 'boundary_uuid' } & BitesGeoListBoundaryUuidErrorComponent | { attr: 'country_id' } & BitesGeoListCountryIdErrorComponent | { attr: 'created_at' } & BitesGeoListCreatedAtErrorComponent | { attr: 'geo_precision' } & BitesGeoListGeoPrecisionErrorComponent | { attr: 'order_by' } & BitesGeoListOrderByErrorComponent | { attr: 'received_at' } & BitesGeoListReceivedAtErrorComponent | { attr: 'short_id' } & BitesGeoListShortIdErrorComponent | { attr: 'tags' } & BitesGeoListTagsErrorComponent | { attr: 'updated_at' } & BitesGeoListUpdatedAtErrorComponent | { attr: 'user_uuid' } & BitesGeoListUserUuidErrorComponent;


