/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BiteCounts {
    /**
     * Total number of bites reported.
     */
    'total': number;
    /**
     * Number of bites reported in the head.
     */
    'head'?: number;
    /**
     * Number of bites reported in the left arm.
     */
    'left_arm'?: number;
    /**
     * Number of bites reported in the right arm.
     */
    'right_arm'?: number;
    /**
     * Number of bites reported in the chest.
     */
    'chest'?: number;
    /**
     * Number of bites reported in the left leg.
     */
    'left_leg'?: number;
    /**
     * Number of bites reported in the right leg.
     */
    'right_leg'?: number;
}

