/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const BitesCreateCountsNonFieldErrorsErrorComponentCode = {
    Invalid: 'invalid',
    Null: 'null',
    Required: 'required',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type BitesCreateCountsNonFieldErrorsErrorComponentCode = typeof BitesCreateCountsNonFieldErrorsErrorComponentCode[keyof typeof BitesCreateCountsNonFieldErrorsErrorComponentCode];



