/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BiteGeoJsonModelProperties } from './bite-geo-json-model-properties';
// May contain unused imports in some cases
// @ts-ignore
import type { BiteGeoJsonModelType } from './bite-geo-json-model-type';

export interface BiteGeoJsonModel {
    'type'?: BiteGeoJsonModelType;
    /**
     * UUID randomly generated on phone to identify each unique report version. Must be exactly 36 characters (32 hex digits plus 4 hyphens).
     */
    'id'?: string;
    'geometry'?: any;
    'properties'?: BiteGeoJsonModelProperties;
}



