/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesCreateEventEnvironmentErrorComponentCode } from './bites-create-event-environment-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesListMineOrderByErrorComponentAttr } from './bites-list-mine-order-by-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineCountryIdErrorComponent } from './breedingsites-list-mine-country-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineCreatedAtErrorComponent } from './breedingsites-list-mine-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineOrderByErrorComponent } from './breedingsites-list-mine-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineReceivedAtErrorComponent } from './breedingsites-list-mine-received-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineShortIdErrorComponent } from './breedingsites-list-mine-short-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineUpdatedAtErrorComponent } from './breedingsites-list-mine-updated-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesListMineUserUuidErrorComponent } from './breedingsites-list-mine-user-uuid-error-component';

/**
 * @type BreedingsitesListMineError
 */
export type BreedingsitesListMineError = { attr: 'country_id' } & BreedingsitesListMineCountryIdErrorComponent | { attr: 'created_at' } & BreedingsitesListMineCreatedAtErrorComponent | { attr: 'order_by' } & BreedingsitesListMineOrderByErrorComponent | { attr: 'received_at' } & BreedingsitesListMineReceivedAtErrorComponent | { attr: 'short_id' } & BreedingsitesListMineShortIdErrorComponent | { attr: 'updated_at' } & BreedingsitesListMineUpdatedAtErrorComponent | { attr: 'user_uuid' } & BreedingsitesListMineUserUuidErrorComponent;


