/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesCreateSiteTypeErrorComponentAttr } from './breedingsites-create-site-type-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListBoundaryUuidErrorComponent } from './breedingsites-geo-list-boundary-uuid-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListCountryIdErrorComponent } from './breedingsites-geo-list-country-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListCreatedAtErrorComponent } from './breedingsites-geo-list-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListGeoPrecisionErrorComponent } from './breedingsites-geo-list-geo-precision-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListOrderByErrorComponent } from './breedingsites-geo-list-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListReceivedAtErrorComponent } from './breedingsites-geo-list-received-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListShortIdErrorComponent } from './breedingsites-geo-list-short-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListSiteTypeErrorComponent } from './breedingsites-geo-list-site-type-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListSiteTypeErrorComponentCode } from './breedingsites-geo-list-site-type-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListTagsErrorComponent } from './breedingsites-geo-list-tags-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListUpdatedAtErrorComponent } from './breedingsites-geo-list-updated-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { BreedingsitesGeoListUserUuidErrorComponent } from './breedingsites-geo-list-user-uuid-error-component';

/**
 * @type BreedingsitesGeoListError
 */
export type BreedingsitesGeoListError = { attr: 'boundary_uuid' } & BreedingsitesGeoListBoundaryUuidErrorComponent | { attr: 'country_id' } & BreedingsitesGeoListCountryIdErrorComponent | { attr: 'created_at' } & BreedingsitesGeoListCreatedAtErrorComponent | { attr: 'geo_precision' } & BreedingsitesGeoListGeoPrecisionErrorComponent | { attr: 'order_by' } & BreedingsitesGeoListOrderByErrorComponent | { attr: 'received_at' } & BreedingsitesGeoListReceivedAtErrorComponent | { attr: 'short_id' } & BreedingsitesGeoListShortIdErrorComponent | { attr: 'site_type' } & BreedingsitesGeoListSiteTypeErrorComponent | { attr: 'tags' } & BreedingsitesGeoListTagsErrorComponent | { attr: 'updated_at' } & BreedingsitesGeoListUpdatedAtErrorComponent | { attr: 'user_uuid' } & BreedingsitesGeoListUserUuidErrorComponent;


