/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AnnotationClassificationRequest } from './annotation-classification-request';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateOverwriteReviewRequestAction } from './create-overwrite-review-request-action';

/**
 * 
 * @export
 * @interface CreateOverwriteReviewRequest
 */
export interface CreateOverwriteReviewRequest {
    /**
     * 
     * @type {CreateOverwriteReviewRequestAction}
     * @memberof CreateOverwriteReviewRequest
     */
    'action'?: CreateOverwriteReviewRequestAction;
    /**
     * 
     * @type {string}
     * @memberof CreateOverwriteReviewRequest
     */
    'public_photo_uuid': string;
    /**
     * Indicates if the content is safe for publication.
     * @type {boolean}
     * @memberof CreateOverwriteReviewRequest
     */
    'is_safe': boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateOverwriteReviewRequest
     */
    'public_note': string | null;
    /**
     * 
     * @type {AnnotationClassificationRequest}
     * @memberof CreateOverwriteReviewRequest
     */
    'result': AnnotationClassificationRequest | null;
}



