/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateOverwriteReviewRequestAction } from './create-overwrite-review-request-action';
// May contain unused imports in some cases
// @ts-ignore
import type { SpeciesCharacteristicsRequest } from './species-characteristics-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SpeciesClassificationRequest } from './species-classification-request';

export interface CreateOverwriteReviewRequest {
    'action': CreateOverwriteReviewRequestAction;
    'public_photo_uuid': string;
    'is_safe': boolean;
    /**
     * Notes to display on public map
     */
    'public_note': string | null;
    'classification': SpeciesClassificationRequest | null;
    'characteristics'?: SpeciesCharacteristicsRequest | null;
}



