/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DevicesCreateMobileAppPackageVersionErrorComponentAttr } from './devices-create-mobile-app-package-version-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesCreateMobileAppPackageVersionErrorComponentCode } from './devices-create-mobile-app-package-version-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateFcmTokenErrorComponent } from './devices-partial-update-fcm-token-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateMobileAppNonFieldErrorsErrorComponent } from './devices-partial-update-mobile-app-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateMobileAppPackageNameErrorComponent } from './devices-partial-update-mobile-app-package-name-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateMobileAppPackageVersionErrorComponent } from './devices-partial-update-mobile-app-package-version-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateNameErrorComponent } from './devices-partial-update-name-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateNonFieldErrorsErrorComponent } from './devices-partial-update-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateOsLocaleErrorComponent } from './devices-partial-update-os-locale-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateOsNameErrorComponent } from './devices-partial-update-os-name-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateOsNonFieldErrorsErrorComponent } from './devices-partial-update-os-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DevicesPartialUpdateOsVersionErrorComponent } from './devices-partial-update-os-version-error-component';

/**
 * @type DevicesPartialUpdateError
 */
export type DevicesPartialUpdateError = { attr: 'fcm_token' } & DevicesPartialUpdateFcmTokenErrorComponent | { attr: 'mobile_app.non_field_errors' } & DevicesPartialUpdateMobileAppNonFieldErrorsErrorComponent | { attr: 'mobile_app.package_name' } & DevicesPartialUpdateMobileAppPackageNameErrorComponent | { attr: 'mobile_app.package_version' } & DevicesPartialUpdateMobileAppPackageVersionErrorComponent | { attr: 'name' } & DevicesPartialUpdateNameErrorComponent | { attr: 'non_field_errors' } & DevicesPartialUpdateNonFieldErrorsErrorComponent | { attr: 'os.locale' } & DevicesPartialUpdateOsLocaleErrorComponent | { attr: 'os.name' } & DevicesPartialUpdateOsNameErrorComponent | { attr: 'os.non_field_errors' } & DevicesPartialUpdateOsNonFieldErrorsErrorComponent | { attr: 'os.version' } & DevicesPartialUpdateOsVersionErrorComponent;


