/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeviceOs } from './device-os';
// May contain unused imports in some cases
// @ts-ignore
import type { DeviceType } from './device-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MobileApp } from './mobile-app';

/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * Unique device identifier
     * @type {string}
     * @memberof Device
     */
    'device_id': string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'name'?: string | null;
    /**
     * 
     * @type {DeviceType}
     * @memberof Device
     */
    'type': DeviceType;
    /**
     * The manufacturer of the device.
     * @type {string}
     * @memberof Device
     */
    'manufacturer'?: string | null;
    /**
     * The end-user-visible name for the end product.
     * @type {string}
     * @memberof Device
     */
    'model': string;
    /**
     * 
     * @type {DeviceOs}
     * @memberof Device
     */
    'os': DeviceOs;
    /**
     * 
     * @type {MobileApp}
     * @memberof Device
     */
    'mobile_app'?: MobileApp;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'user_uuid': string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'last_login': string | null;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'updated_at': string;
}



