/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FixesCreatePointLatitudeErrorComponentAttr } from './fixes-create-point-latitude-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { FixesCreatePointLatitudeErrorComponentCode } from './fixes-create-point-latitude-error-component-code';

/**
 * 
 * @export
 * @interface FixesCreatePointLatitudeErrorComponent
 */
export interface FixesCreatePointLatitudeErrorComponent {
    /**
     * 
     * @type {FixesCreatePointLatitudeErrorComponentAttr}
     * @memberof FixesCreatePointLatitudeErrorComponent
     */
    'attr': FixesCreatePointLatitudeErrorComponentAttr;
    /**
     * 
     * @type {FixesCreatePointLatitudeErrorComponentCode}
     * @memberof FixesCreatePointLatitudeErrorComponent
     */
    'code': FixesCreatePointLatitudeErrorComponentCode;
    /**
     * 
     * @type {string}
     * @memberof FixesCreatePointLatitudeErrorComponent
     */
    'detail': string;
}



