/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesListCreatedAtErrorComponentCode } from './bites-list-created-at-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineAnnotatorIdsErrorComponent } from './identificationtasks-list-mine-annotator-ids-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineCreatedAtErrorComponent } from './identificationtasks-list-mine-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineNumAnnotationsErrorComponent } from './identificationtasks-list-mine-num-annotations-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineNumAssignationsErrorComponent } from './identificationtasks-list-mine-num-assignations-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineObservationCountryErrorComponent } from './identificationtasks-list-mine-observation-country-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineOrderByErrorComponent } from './identificationtasks-list-mine-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineResultAgreementErrorComponent } from './identificationtasks-list-mine-result-agreement-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineResultAgreementErrorComponentAttr } from './identificationtasks-list-mine-result-agreement-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineResultConfidenceErrorComponent } from './identificationtasks-list-mine-result-confidence-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineResultTaxonErrorComponent } from './identificationtasks-list-mine-result-taxon-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineResultUncertaintyErrorComponent } from './identificationtasks-list-mine-result-uncertainty-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineReviewTypeErrorComponent } from './identificationtasks-list-mine-review-type-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineStatusErrorComponent } from './identificationtasks-list-mine-status-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListMineUpdatedAtErrorComponent } from './identificationtasks-list-mine-updated-at-error-component';

/**
 * @type IdentificationtasksListMineError
 * @export
 */
export type IdentificationtasksListMineError = { attr: 'annotator_ids' } & IdentificationtasksListMineAnnotatorIdsErrorComponent | { attr: 'created_at' } & IdentificationtasksListMineCreatedAtErrorComponent | { attr: 'num_annotations' } & IdentificationtasksListMineNumAnnotationsErrorComponent | { attr: 'num_assignations' } & IdentificationtasksListMineNumAssignationsErrorComponent | { attr: 'observation_country' } & IdentificationtasksListMineObservationCountryErrorComponent | { attr: 'order_by' } & IdentificationtasksListMineOrderByErrorComponent | { attr: 'result_agreement' } & IdentificationtasksListMineResultAgreementErrorComponent | { attr: 'result_confidence' } & IdentificationtasksListMineResultConfidenceErrorComponent | { attr: 'result_taxon' } & IdentificationtasksListMineResultTaxonErrorComponent | { attr: 'result_uncertainty' } & IdentificationtasksListMineResultUncertaintyErrorComponent | { attr: 'review_type' } & IdentificationtasksListMineReviewTypeErrorComponent | { attr: 'status' } & IdentificationtasksListMineStatusErrorComponent | { attr: 'updated_at' } & IdentificationtasksListMineUpdatedAtErrorComponent;


