/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesCreateEventEnvironmentErrorComponentCode } from './bites-create-event-environment-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesListMineOrderByErrorComponentAttr } from './bites-list-mine-order-by-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListAssigneesErrorComponent } from './identificationtasks-list-assignees-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListCreatedAtErrorComponent } from './identificationtasks-list-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListNumAnnotationsErrorComponent } from './identificationtasks-list-num-annotations-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListNumAssignationsErrorComponent } from './identificationtasks-list-num-assignations-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListOrderByErrorComponent } from './identificationtasks-list-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListRevisionTypeErrorComponent } from './identificationtasks-list-revision-type-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListStatusErrorComponent } from './identificationtasks-list-status-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationtasksListUpdatedAtErrorComponent } from './identificationtasks-list-updated-at-error-component';

/**
 * @type IdentificationtasksListError
 * @export
 */
export type IdentificationtasksListError = { attr: 'assignees' } & IdentificationtasksListAssigneesErrorComponent | { attr: 'created_at' } & IdentificationtasksListCreatedAtErrorComponent | { attr: 'num_annotations' } & IdentificationtasksListNumAnnotationsErrorComponent | { attr: 'num_assignations' } & IdentificationtasksListNumAssignationsErrorComponent | { attr: 'order_by' } & IdentificationtasksListOrderByErrorComponent | { attr: 'revision_type' } & IdentificationtasksListRevisionTypeErrorComponent | { attr: 'status' } & IdentificationtasksListStatusErrorComponent | { attr: 'updated_at' } & IdentificationtasksListUpdatedAtErrorComponent;


