/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A custom serializer field that supports localization for a dynamic field name. Allows calling with arguments such as \'title\', \'message\', max_length, help_text, etc.
 * @export
 * @interface LocalizedMessageTitleRequest
 */
export interface LocalizedMessageTitleRequest {
    /**
     * Български
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'bg'?: string;
    /**
     * বাংলা
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'bn'?: string;
    /**
     * Català
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'ca'?: string;
    /**
     * Deutsch
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'de'?: string;
    /**
     * Ελληνικά
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'el'?: string;
    /**
     * English
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'en': string;
    /**
     * Español
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'es'?: string;
    /**
     * Euskara
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'eu'?: string;
    /**
     * Français
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'fr'?: string;
    /**
     * Galego
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'gl'?: string;
    /**
     * Hrvatski
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'hr'?: string;
    /**
     * Magyar
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'hu'?: string;
    /**
     * Italiano
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'it'?: string;
    /**
     * Lëtzebuergesch
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'lb'?: string;
    /**
     * Македонски
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'mk'?: string;
    /**
     * Nederlands
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'nl'?: string;
    /**
     * Português
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'pt'?: string;
    /**
     * Română
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'ro'?: string;
    /**
     * Slovenščina
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'sl'?: string;
    /**
     * Shqip
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'sq'?: string;
    /**
     * Српски
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'sr'?: string;
    /**
     * Svenska
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'sv'?: string;
    /**
     * Türkçe
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'tr'?: string;
    /**
     * 中文（中国）
     * @type {string}
     * @memberof LocalizedMessageTitleRequest
     */
    'zh-CN'?: string;
}

