/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationsPartialUpdateIsReadErrorComponentAttr } from './notifications-partial-update-is-read-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationsPartialUpdateIsReadErrorComponentCode } from './notifications-partial-update-is-read-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationsUpdateIsReadErrorComponent } from './notifications-update-is-read-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationsUpdateNonFieldErrorsErrorComponent } from './notifications-update-non-field-errors-error-component';

/**
 * @type NotificationsUpdateError
 * @export
 */
export type NotificationsUpdateError = { attr: 'is_read' } & NotificationsUpdateIsReadErrorComponent | { attr: 'non_field_errors' } & NotificationsUpdateNonFieldErrorsErrorComponent;


