/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthChangePasswordValidationErrorType } from './auth-change-password-validation-error-type';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationsListMineError } from './notifications-list-mine-error';

/**
 * 
 * @export
 * @interface NotificationsListMineValidationError
 */
export interface NotificationsListMineValidationError {
    /**
     * 
     * @type {AuthChangePasswordValidationErrorType}
     * @memberof NotificationsListMineValidationError
     */
    'type': AuthChangePasswordValidationErrorType;
    /**
     * 
     * @type {Array<NotificationsListMineError>}
     * @memberof NotificationsListMineValidationError
     */
    'errors': Array<NotificationsListMineError>;
}



