/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BiteEventEnvironment } from './bite-event-environment';
// May contain unused imports in some cases
// @ts-ignore
import type { BiteEventMoment } from './bite-event-moment';
// May contain unused imports in some cases
// @ts-ignore
import type { Identification } from './identification';
// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import type { MosquitoAppearance } from './mosquito-appearance';
// May contain unused imports in some cases
// @ts-ignore
import type { SimplePhoto } from './simple-photo';

export interface Observation {
    'uuid': string;
    'short_id': string;
    'user_uuid': string;
    'created_at': string;
    /**
     * The date and time when the record was created, displayed in the local timezone specified for this entry.
     */
    'created_at_local': string;
    'sent_at': string;
    'received_at': string;
    /**
     * Date and time when the report was last modified
     */
    'updated_at': string;
    'location': Location;
    /**
     * Note user attached to report.
     */
    'note'?: string | null;
    'tags'?: Array<string>;
    'published': boolean;
    'photos': Array<SimplePhoto>;
    'identification': Identification | null;
    'event_environment'?: BiteEventEnvironment | null;
    'event_moment'?: BiteEventMoment | null;
    /**
     * User-provided description of the mosquito\'s appearance
     */
    'mosquito_appearance'?: MosquitoAppearance | null;
}



