/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesListMineShortIdErrorComponentAttr } from './bites-list-mine-short-id-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { BitesListMineShortIdErrorComponentCode } from './bites-list-mine-short-id-error-component-code';

/**
 * 
 * @export
 * @interface ObservationsListMineShortIdErrorComponent
 */
export interface ObservationsListMineShortIdErrorComponent {
    /**
     * 
     * @type {BitesListMineShortIdErrorComponentAttr}
     * @memberof ObservationsListMineShortIdErrorComponent
     */
    'attr': BitesListMineShortIdErrorComponentAttr;
    /**
     * 
     * @type {BitesListMineShortIdErrorComponentCode}
     * @memberof ObservationsListMineShortIdErrorComponent
     */
    'code': BitesListMineShortIdErrorComponentCode;
    /**
     * 
     * @type {string}
     * @memberof ObservationsListMineShortIdErrorComponent
     */
    'detail': string;
}



