/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesCreateEventEnvironmentErrorComponentCode } from './bites-create-event-environment-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListBoundaryUuidErrorComponent } from './observations-geo-list-boundary-uuid-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListCountryIdErrorComponent } from './observations-geo-list-country-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListCreatedAtErrorComponent } from './observations-geo-list-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListGeoPrecisionErrorComponent } from './observations-geo-list-geo-precision-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListIdentificationTaxonIdsErrorComponent } from './observations-geo-list-identification-taxon-ids-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListIdentificationTaxonIdsLookupErrorComponent } from './observations-geo-list-identification-taxon-ids-lookup-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListIdentificationTaxonIdsLookupErrorComponentAttr } from './observations-geo-list-identification-taxon-ids-lookup-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListOrderByErrorComponent } from './observations-geo-list-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListReceivedAtErrorComponent } from './observations-geo-list-received-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListShortIdErrorComponent } from './observations-geo-list-short-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListTagsErrorComponent } from './observations-geo-list-tags-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListUpdatedAtErrorComponent } from './observations-geo-list-updated-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListUserUuidErrorComponent } from './observations-geo-list-user-uuid-error-component';

/**
 * @type ObservationsGeoListError
 */
export type ObservationsGeoListError = { attr: 'boundary_uuid' } & ObservationsGeoListBoundaryUuidErrorComponent | { attr: 'country_id' } & ObservationsGeoListCountryIdErrorComponent | { attr: 'created_at' } & ObservationsGeoListCreatedAtErrorComponent | { attr: 'geo_precision' } & ObservationsGeoListGeoPrecisionErrorComponent | { attr: 'identification_taxon_ids' } & ObservationsGeoListIdentificationTaxonIdsErrorComponent | { attr: 'identification_taxon_ids_lookup' } & ObservationsGeoListIdentificationTaxonIdsLookupErrorComponent | { attr: 'order_by' } & ObservationsGeoListOrderByErrorComponent | { attr: 'received_at' } & ObservationsGeoListReceivedAtErrorComponent | { attr: 'short_id' } & ObservationsGeoListShortIdErrorComponent | { attr: 'tags' } & ObservationsGeoListTagsErrorComponent | { attr: 'updated_at' } & ObservationsGeoListUpdatedAtErrorComponent | { attr: 'user_uuid' } & ObservationsGeoListUserUuidErrorComponent;


