/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesCreateEventEnvironmentErrorComponentCode } from './bites-create-event-environment-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateCreatedAtErrorComponent } from './observations-create-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateEventEnvironmentErrorComponent } from './observations-create-event-environment-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateEventMomentErrorComponent } from './observations-create-event-moment-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateLocationNonFieldErrorsErrorComponent } from './observations-create-location-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateLocationPointLatitudeErrorComponent } from './observations-create-location-point-latitude-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateLocationPointLongitudeErrorComponent } from './observations-create-location-point-longitude-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateLocationPointNonFieldErrorsErrorComponent } from './observations-create-location-point-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateLocationSourceErrorComponent } from './observations-create-location-source-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceAbdomenErrorComponent } from './observations-create-mosquito-appearance-abdomen-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceLegsErrorComponent } from './observations-create-mosquito-appearance-legs-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceLegsErrorComponentAttr } from './observations-create-mosquito-appearance-legs-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent } from './observations-create-mosquito-appearance-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceSpecieErrorComponent } from './observations-create-mosquito-appearance-specie-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceThoraxErrorComponent } from './observations-create-mosquito-appearance-thorax-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateNonFieldErrorsErrorComponent } from './observations-create-non-field-errors-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateNoteErrorComponent } from './observations-create-note-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreatePhotosErrorComponent } from './observations-create-photos-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreatePhotosINDEXErrorComponent } from './observations-create-photos-indexerror-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateSentAtErrorComponent } from './observations-create-sent-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateTagsErrorComponent } from './observations-create-tags-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateTagsINDEXErrorComponent } from './observations-create-tags-indexerror-component';

/**
 * @type ObservationsCreateError
 */
export type ObservationsCreateError = { attr: 'created_at' } & ObservationsCreateCreatedAtErrorComponent | { attr: 'event_environment' } & ObservationsCreateEventEnvironmentErrorComponent | { attr: 'event_moment' } & ObservationsCreateEventMomentErrorComponent | { attr: 'location.non_field_errors' } & ObservationsCreateLocationNonFieldErrorsErrorComponent | { attr: 'location.point.latitude' } & ObservationsCreateLocationPointLatitudeErrorComponent | { attr: 'location.point.longitude' } & ObservationsCreateLocationPointLongitudeErrorComponent | { attr: 'location.point.non_field_errors' } & ObservationsCreateLocationPointNonFieldErrorsErrorComponent | { attr: 'location.source' } & ObservationsCreateLocationSourceErrorComponent | { attr: 'mosquito_appearance.abdomen' } & ObservationsCreateMosquitoAppearanceAbdomenErrorComponent | { attr: 'mosquito_appearance.legs' } & ObservationsCreateMosquitoAppearanceLegsErrorComponent | { attr: 'mosquito_appearance.non_field_errors' } & ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent | { attr: 'mosquito_appearance.specie' } & ObservationsCreateMosquitoAppearanceSpecieErrorComponent | { attr: 'mosquito_appearance.thorax' } & ObservationsCreateMosquitoAppearanceThoraxErrorComponent | { attr: 'non_field_errors' } & ObservationsCreateNonFieldErrorsErrorComponent | { attr: 'note' } & ObservationsCreateNoteErrorComponent | { attr: 'photos' } & ObservationsCreatePhotosErrorComponent | { attr: 'photos.INDEX' } & ObservationsCreatePhotosINDEXErrorComponent | { attr: 'sent_at' } & ObservationsCreateSentAtErrorComponent | { attr: 'tags' } & ObservationsCreateTagsErrorComponent | { attr: 'tags.INDEX' } & ObservationsCreateTagsINDEXErrorComponent;


