/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesCreateEventEnvironmentErrorComponentCode } from './bites-create-event-environment-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsGeoListIdentificationTaxonIdsLookupErrorComponentAttr } from './observations-geo-list-identification-taxon-ids-lookup-error-component-attr';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineBoundaryUuidErrorComponent } from './observations-list-mine-boundary-uuid-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineCountryIdErrorComponent } from './observations-list-mine-country-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineCreatedAtErrorComponent } from './observations-list-mine-created-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineGeoPrecisionErrorComponent } from './observations-list-mine-geo-precision-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineIdentificationTaxonIdsErrorComponent } from './observations-list-mine-identification-taxon-ids-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineIdentificationTaxonIdsLookupErrorComponent } from './observations-list-mine-identification-taxon-ids-lookup-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineOrderByErrorComponent } from './observations-list-mine-order-by-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineReceivedAtErrorComponent } from './observations-list-mine-received-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineShortIdErrorComponent } from './observations-list-mine-short-id-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineTagsErrorComponent } from './observations-list-mine-tags-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineUpdatedAtErrorComponent } from './observations-list-mine-updated-at-error-component';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsListMineUserUuidErrorComponent } from './observations-list-mine-user-uuid-error-component';

/**
 * @type ObservationsListMineError
 */
export type ObservationsListMineError = { attr: 'boundary_uuid' } & ObservationsListMineBoundaryUuidErrorComponent | { attr: 'country_id' } & ObservationsListMineCountryIdErrorComponent | { attr: 'created_at' } & ObservationsListMineCreatedAtErrorComponent | { attr: 'geo_precision' } & ObservationsListMineGeoPrecisionErrorComponent | { attr: 'identification_taxon_ids' } & ObservationsListMineIdentificationTaxonIdsErrorComponent | { attr: 'identification_taxon_ids_lookup' } & ObservationsListMineIdentificationTaxonIdsLookupErrorComponent | { attr: 'order_by' } & ObservationsListMineOrderByErrorComponent | { attr: 'received_at' } & ObservationsListMineReceivedAtErrorComponent | { attr: 'short_id' } & ObservationsListMineShortIdErrorComponent | { attr: 'tags' } & ObservationsListMineTagsErrorComponent | { attr: 'updated_at' } & ObservationsListMineUpdatedAtErrorComponent | { attr: 'user_uuid' } & ObservationsListMineUserUuidErrorComponent;


