/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BitesListCreatedAtErrorComponentCode } from './bites-list-created-at-error-component-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponentAttr } from './observations-create-mosquito-appearance-non-field-errors-error-component-attr';

/**
 * 
 * @export
 * @interface ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent
 */
export interface ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent {
    /**
     * 
     * @type {ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponentAttr}
     * @memberof ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent
     */
    'attr': ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponentAttr;
    /**
     * 
     * @type {BitesListCreatedAtErrorComponentCode}
     * @memberof ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent
     */
    'code': BitesListCreatedAtErrorComponentCode;
    /**
     * 
     * @type {string}
     * @memberof ObservationsCreateMosquitoAppearanceNonFieldErrorsErrorComponent
     */
    'detail': string;
}



