/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The locale code representing the language preference selected by the user for displaying the interface text. Enter the locale following the BCP 47 standard in \'language\' or \'language-region\' format (e.g., \'en\' for English, \'en-US\' for English (United States), \'fr\' for French). The language is a two-letter ISO 639-1 code, and the region is an optional two-letter ISO 3166-1 alpha-2 code.
 * @export
 * @enum {string}
 */

export const PatchedUserRequestLocale = {
    Es: 'es',
    Ca: 'ca',
    Eu: 'eu',
    Bn: 'bn',
    Sv: 'sv',
    En: 'en',
    De: 'de',
    Sq: 'sq',
    El: 'el',
    Gl: 'gl',
    Hu: 'hu',
    Pt: 'pt',
    Sl: 'sl',
    It: 'it',
    Fr: 'fr',
    Bg: 'bg',
    Ro: 'ro',
    Hr: 'hr',
    Mk: 'mk',
    Sr: 'sr',
    Lb: 'lb',
    Nl: 'nl',
    Tr: 'tr',
    ZhMinusCn: 'zh-CN',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type PatchedUserRequestLocale = typeof PatchedUserRequestLocale[keyof typeof PatchedUserRequestLocale];



