/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AnnotationPermission } from './annotation-permission';
// May contain unused imports in some cases
// @ts-ignore
import type { IdentificationTaskPermission } from './identification-task-permission';
// May contain unused imports in some cases
// @ts-ignore
import type { ReviewPermission } from './review-permission';

/**
 * 
 * @export
 * @interface Permissions
 */
export interface Permissions {
    /**
     * 
     * @type {AnnotationPermission}
     * @memberof Permissions
     */
    'annotation': AnnotationPermission;
    /**
     * 
     * @type {IdentificationTaskPermission}
     * @memberof Permissions
     */
    'identification_task': IdentificationTaskPermission;
    /**
     * 
     * @type {ReviewPermission}
     * @memberof Permissions
     */
    'review': ReviewPermission;
}

