/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SimpleTaxonRank } from './simple-taxon-rank';

/**
 * 
 * @export
 * @interface TaxonTreeNode
 */
export interface TaxonTreeNode {
    /**
     * 
     * @type {number}
     * @memberof TaxonTreeNode
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof TaxonTreeNode
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TaxonTreeNode
     */
    'common_name'?: string | null;
    /**
     * 
     * @type {SimpleTaxonRank}
     * @memberof TaxonTreeNode
     */
    'rank': SimpleTaxonRank;
    /**
     * Display the name in italics when rendering.
     * @type {boolean}
     * @memberof TaxonTreeNode
     */
    'italicize': boolean;
    /**
     * Indicates if this taxon is relevant for the application. Will be shown first and will set task to conflict if final taxon is not this.
     * @type {boolean}
     * @memberof TaxonTreeNode
     */
    'is_relevant': boolean;
    /**
     * 
     * @type {Array<TaxonTreeNode>}
     * @memberof TaxonTreeNode
     */
    'children': Array<TaxonTreeNode>;
}



