/* tslint:disable */
/* eslint-disable */
/**
 * Mosquito Alert API
 * Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
 *
 * The version of the OpenAPI document: v1
 * Contact: it@mosquitoalert.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MinimalUserLocale } from './minimal-user-locale';
// May contain unused imports in some cases
// @ts-ignore
import type { UserScore } from './user-score';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'full_name': string;
    /**
     * The date and time when user registered and consented to sharing data. Automatically set by server when user uploads registration.
     * @type {string}
     * @memberof User
     */
    'registration_time': string;
    /**
     * 
     * @type {MinimalUserLocale}
     * @memberof User
     */
    'locale'?: MinimalUserLocale;
    /**
     * ISO 639-1 code
     * @type {string}
     * @memberof User
     */
    'language_iso': string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_guest': boolean;
    /**
     * 
     * @type {UserScore}
     * @memberof User
     */
    'score': UserScore;
}



